#!/bin/bash


chmod +x ~/binder/start.hadoop 
chmod +x ~/binder/start.zookeeper
chmod +x ~/binder/start.kafka




~/binder/start.hadoop  		&& \
sleep 3                		&& \
~/binder/start.zookeeper    && \
sleep 3                		&& \
~/binder/start.kafka   		&& \
touch ready.txt         	&



# DO NOT REMOVE(!) 
# Here is why: https://mybinder.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"